services:
  nextjs:
    build:
      context: .
    container_name: nextjs_app
    restart: always
    environment: 
      - NODE_ENV=production
      - HOST=0.0.0.0
    networks:
      - app-network

  nginx-certbot:
    build:
      context: ./nginx
    container_name: nginx-certbot
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - nextjs

networks:
  app-network:
    driver: bridge
