name: Build and Start Next.js Application

on: [push, pull_request]

jobs:
  start-server:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
          
      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres" >> .env

      - name: Push schema to database
        run: npx prisma db push

      - name: Seed database
        run: npx prisma db seed

      - name: Build application
        run: npm run build

      - name: Lint with ESLint
        run: npm run lint

      - name: Start application
        run: npm start & echo $! > app.pid

      - name: Wait for application to start
        run: sleep 10

      - name: Kill application
        run: kill $(cat app.pid) || true

      - name: Remove temporary artifacts
        run: rm -f app.pid
