name: Build and Start Next.js Application

on: [push, pull_request]

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Lint with ESLint
        run: npm run lint

      - name: Start application
        run: npm start & echo $! > app.pid

      - name: Wait for application to start
        run: sleep 10

      - name: Kill application
        run: kill $(cat app.pid) || true

      - name: Remove temporary artifacts
        run: rm -f app.pid
